In [2]:
from sklearn.preprocessing import LabelEncoder

# traing 데이터만 학습 시켜야 한다.
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','냉장고','TV']

encoder = LabelEncoder()

result = encoder.fit_transform(items)
result

array([0, 1, 3, 4, 2, 1, 0])

In [3]:
encoder.classes_

array(['TV', '냉장고', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [4]:
# 결과를 숫자로 반환, 문자로 변환하는 명령
result = encoder.inverse_transform([3,1,2])
result

array(['전자레인지', '냉장고', '선풍기'], dtype='<U5')

In [5]:
items2 = ['운동장','실내체육관','수영장','교무실','강당','수영장','강당','수영장']
result2 = encoder.fit_transform(items2)
result2

array([4, 3, 2, 1, 0, 2, 0, 2])

In [ ]:
result2 = encoder.inverse_transform([3,2,1])
result2

array(['실내체육관', '수영장', '교무실'], dtype='<U5')

In [16]:
import pandas as pd

data = pd.read_excel('./data/인터넷가입자이탈현황_v01.xlsx', engine='openpyxl')
data.head()

고객ID  월평균사용량_GB  가입기간_년   이탈여부
0   101       15.5       3   Stay
1   102        2.1       1  Churn
2   103       30.0       5   Stay
3   104        5.5       2   Stay
4   105        1.0       1  Churn

In [17]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
result = encoder.fit_transform(data["이탈여부"])
result

array([1, 0, 1, 1, 0, 1])

In [21]:
data['이탈여부'] = result
data.head()
data_raw = data.copy()

In [23]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

data2 = {
    'age' : [25,35,45,50],
    'salary' : [2500,4800,7100,5200]
}

df2 = pd.DataFrame(data2)
df2.head()

age  salary
0   25    2500
1   35    4800
2   45    7100
3   50    5200

In [25]:
#2 표준화
scaler2 = StandardScaler()

result2 = scaler2.fit_transform(df2) 
result2

array([[-1.43207802, -1.46740282],
       [-0.39056673, -0.06114178],
       [ 0.65094455,  1.34511925],
       [ 1.1717002 ,  0.18342535]])

In [27]:
scaled_df2 = pd.DataFrame(result2,columns=df2.columns)
scaled_df2

age    salary
0 -1.432078 -1.467403
1 -0.390567 -0.061142
2  0.650945  1.345119
3  1.171700  0.183425

In [30]:
my_data = [[27,100000000]]
my_data_scaled = scaler2.transform(my_data)
my_data_scaled

c:\potenup3\prj_learn\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.22377576e+00,  6.11387881e+04]])

In [31]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np


data2 = {
    'age' : [25,35,45,50],
    'salary' : [2500,4800,7100,5200]
}
df2 = pd.DataFrame(data2)
df2.head()

age  salary
0   25    2500
1   35    4800
2   45    7100
3   50    5200

In [32]:
scaler2 = MinMaxScaler()
scaled_df2 = scaler2.fit_transform(df2)
scaled_df2

array([[0.        , 0.        ],
       [0.4       , 0.5       ],
       [0.8       , 1.        ],
       [1.        , 0.58695652]])

In [116]:
train_data = pd.read_excel('./data/train_dataset.xlsx')
test_data = pd.read_excel('./data/test_dataset.xlsx')
train_data_raw = train_data.copy()
test_data_raw = test_data.copy()
train_data.head()
test_data.head()

Age  Experience(Years)  Salary(만원)  Purchased
0   35                 10        7162          1
1   54                 31        7057          1
2   25                  0        8469          0
3   39                  1        5029          0
4   43                  4        7145          0

In [118]:
# train_data_scaled = scaler.fit_transform(train_data)
# train_data_scaled = pd.DataFrame(train_data_scaled,columns=train_data.columns)
# train_data_scaled
X_train = train_data.drop('Purchased',axis=1)
X_train

Age  Experience(Years)  Salary(만원)
0     29                  0        5253
1     37                  7        4143
2     28                  5        7467
3     27                  4        6456
4     24                  0        3767
..   ...                ...         ...
115   22                  0        3848
116   30                  4        3945
117   28                  5        7532
118   31                  4        5308
119   60                 13        5808

[120 rows x 3 columns]

In [120]:
y_tran = train_data["Purchased"]
y_tran

0      0
1      0
2      0
3      0
4      0
      ..
115    0
116    0
117    0
118    0
119    0
Name: Purchased, Length: 120, dtype: int64

In [ ]:
scaler = StandardScaler()
train_data_scaled = scaler.fit_transform(X_train)
train_data_scaled = pd.DataFrame(train_data_scaled,columns=X_train.columns)

train_data_scaled.head()

Age  Experience(Years)  Salary(만원)
0 -1.118542          -1.049940   -0.180599
1 -0.412095          -0.196165   -0.959480
2 -1.206848          -0.440101    1.372954
3 -1.295154          -0.562069    0.663540
4 -1.560072          -1.049940   -1.223317

In [125]:
# 학습진행
X_test = test_data.drop("Purchased",axis=1)
y_test = test_data["Purchased"]

In [ ]:
test_data_scaled = scaler.transform(X_test)

In [ ]:
# GridSearchCV - 하이퍼파라미터를 자동으로 탐색하면서, 교차검증(Cross-Validation)까지 함께 수행
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split


